### ISSUE TITLE
Cargo.toml publising workflow

### ISSUE THREAD

**Issue by mrchantey** [mrchantey/beetmash#1]
People should be able to declare scenes in the same style as binaries/tests/examples.
We can peek at the tarball of published crstes when requested to collect declared scenes, resolving their dependencies/includes using the Cargo.lock

Note: Even though scenes are loaded in a similar way to opaque assets like textures, they behave more like code when it comes to version control and dependency resolution.

Example declaration
```toml
[[package.metadata.scene]]
name = "my-scene"
include = [
  "some-crate/their-scene"
]
app.js-url = "http://storage.com/path.js"
app.wasm-url = "http://storage.com/path.wasm"
app.events = ["on_user_message"]

```
